### ISSUE TITLE
g++: error: `pkg-config: No such file or directory

### ISSUE THREAD

**Issue by sainimohit23** [arthurflor23/text-segmentation#1]
Hi Arthur,

While running your code I am getting this:

![Screenshot_89](https://user-images.githubusercontent.com/26195811/59248118-20a4a480-8c3f-11e9-85fc-2eeae404c9f3.png)

Can you tell me how to deal with this? I am running your code on Windows with anaconda.

**Comment by arthurflor23** [comment]
Hi! 
I just answered in the medium. Anyway, this flags was necessary in Arch Linux to run with OpenCV 4.x. Maybe you can try remove them (src/imgproc/__init__.py) to solve.

Let me know if it works, then I'll remove the flags.

**Comment by sainimohit23** [comment]
This is the error:

![Screenshot_90](https://user-images.githubusercontent.com/26195811/59249203-dd980080-8c41-11e9-8ccb-0aaa3cabc400.png)


Do I have to install additional packages for c++? If yes, can you please tell me how to do that?

**Comment by arthurflor23** [comment]
Remove `pkg-config opencv4` too.
You have installed opencv 4.x? I think that will work directly
