### ISSUE TITLE
error: ‘Rect2d’ was not declared in this scope

### ISSUE THREAD

**Issue by trungna1374** [arthurflor23/text-segmentation#3]
I tried to run. But i have a problem. any idea?
opencv version: 2.4.9.1

**Comment by arthurflor23** [comment]
Hi,
I think it's the version of opencv. Try version 3+, maybe help

**Comment by trungna1374** [comment]
> Hi,
> I think it's the version of opencv. Try version 3+, maybe help

Hi,

**Comment by arthurflor23** [comment]
Hi!
I developed on Arch linux with ``opencv`` (4.1.2-2) package.
And I recently tested it on Ubuntu with the ``libopencv-dev`` (3.2.0) package.
