### ISSUE TITLE
Input images getting warped and group of words getting segmented as one.

### ISSUE THREAD

**Issue by TheFirstMe** [arthurflor23/text-segmentation#7]
I tried giving the program my own input by writing a line of text and taking a photo with my phone. But the image gets warped. How can I fix this? Should the images obey certain formats? 

Also testing on images from IAM dataset kind of works. The lines are correctly segmented. But some words are segmented as a group instead of separate. I'm guessing it's because of the small inter-word distances.

**Comment by TheFirstMe** [comment]
Here's my input image.

![Custom image](https://user-images.githubusercontent.com/23120939/77233588-8d859b80-6bce-11ea-88a5-7347a87b2445.png)

And the cropped image by the program:

![018_1_crop](https://user-images.githubusercontent.com/23120939/77233623-bb6ae000-6bce-11ea-93f7-85e139c92f04.png)

**Comment by arthurflor23** [comment]
Hi,
Words segmented into groups, you must fit the parameters to your context problem, such as ``chunksNumber``, ``chunksProcess``, binarization process or maybe the kernel values to word segmentation (last step).

About your input, try to ignore the "Scanner" process (step 1) and use the default image instead ``imageCropped``

**Comment by TheFirstMe** [comment]
Thanks @arthurflor23 Ignoring Step 1 and using the default image solved the warping issue. 

So is the Scanner process not necessary? Or should I only use it if my input image should be cropped automatically as the app CamScanner?

**Comment by TheFirstMe** [comment]
If the input images contains different writing styles, will changing the parameters matter? Or maybe I should keep a constraint for having certain distance between words?

**Comment by TheFirstMe** [comment]
Another issue that I want to point out is how I ran this project. I am running on Lubuntu 19.10 and I was facing problems running this project. I had to change linux2 to linux and python-opencv to libopencv-dev in the __init__.py in imgproc.

**Comment by TheFirstMe** [comment]
I tried the docker image that you mentioned in a closed issue and it was working fine there. I installed the same dependencies and still I had to make the above mentioned modifications before actually running the program.

**Comment by TheFirstMe** [comment]
These are the changes that I made
```
if sys.platform == "linux":
	cmd += " -std=c++17 -lstdc++fs `pkg-config --cflags --libs opencv`"
```

Without those flags I was getting a "filesystem is not a namespace-name" error from main.cpp python-opencv was not found in pkg-config however libopencv-dev was.

**Comment by arthurflor23** [comment]
> Thanks @arthurflor23 Ignoring Step 1 and using the default image solved the warping issue.
> 
> So is the Scanner process not necessary? Or should I only use it if my input image should be cropped automatically as the app CamScanner?

Only if your input is already fine, you don't need this step. Scanner is just to input papers images (with borders).

> If the input images contains different writing styles, will changing the parameters matter? Or maybe I should keep a constraint for having certain distance between words?

It matters a bit.. depends on the pattern of the image and writing, unfortunately.

The issues are normal.. The ``libopencv-dev`` is necessary because you use opencv from c++, not python.

**Comment by TheFirstMe** [comment]
![0341C9A8-6EBB-445D-935E-E6675E9FDF25](https://user-images.githubusercontent.com/23120939/77366220-96689f80-6d7d-11ea-937e-35ef3cea961c.jpeg)

I tried using the step 1 process on the above image (with initial setup). But the image is not being cropped. Instead it’s like a scanned version without the cropping. The lines and words are being detected though. But some unwanted areas are also detected as words because it was not cropped.

**Comment by arthurflor23** [comment]
You can try to change the values of the processEdge function to suit your images. Unfortunately this process with 'classic' techniques has to be adjusted manually

**Comment by TheFirstMe** [comment]
Any suggestions on what the new values should be?

**Comment by arthurflor23** [comment]
Unfortunately not, my friend

**Comment by TheFirstMe** [comment]
No problem. Thanks for the help
