### ISSUE TITLE
compiling error 

### ISSUE THREAD

**Issue by deeraj** [arthurflor23/text-segmentation#8]
Error with `opencv` tag.
Compiling with `opencv4`...

imgproc/cpp/main.cpp:5:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Preprocess compilation error.

and also tried by adding 
#include <experimental/filesystem>
namespace fs = std::experimental;

namespace fs = std::experimental;

**Comment by arthurflor23** [comment]
What version of gcc?

**Comment by deeraj** [comment]
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)

**Comment by arthurflor23** [comment]
I think that is the same problem [here](https://github.com/arthurflor23/text-segmentation/issues/2#issuecomment-584861047). Try update gcc and g++ to version 8+.

**Comment by deeraj** [comment]
thanks you . works fine. thanks for your quick response
